name: Leafcutter Indexer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  workflow_dispatch:

permissions:
  contents: write  # Required for auto-committing

jobs:
  index:
    uses: "smaudd/leafcutter/.github/workflows/indexer.yml@main"
    with:
      go-version: "1.21"
